[build]
  command = "npm run build"
  publish = "build"
  base = "waati-ai-pwa"

[build.environment]
  NODE_VERSION = "18"
  PUBLIC_URL = "/learning"

[[redirects]]
  from = "/"
  to = "/learning/"
  status = 301

[[redirects]]
  from = "/learning/*"
  to = "/learning/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;" 